config/routes.rb
RailsApp::Application.routes.draw do

  
  root :to => "home#index"
  get 'pictures', to: 'home#pictures', as: 'pictures'
  get 'events', to: 'home#events', as: 'events'
  get 'milestones', to: 'home#milestones', as: 'milestones'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def pictures
  end

  def events
  end

  def milestones
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/events.html.erb
<% content_for :title, "Events - baby.lalcohol.com" %>



<h3>Events </h3>

Here is a summary of what is happening!
<br/><br/>
<ul>

<br/><li>First Obstetrician Visit<br/><small>May 20, 2013</small></li>

<br/><li>First Sonagraph Picture<br/><small>May 20, 2013</small></li>

<br/><li>Heard Heartbeat<br/><small>June 11, 2013</small></li>

<br/><li>Appearance of a Baby Bump<br/><small>July 12, 2013</small></li>

<br/><li>Baby Announcement<br/><small>July 18, 2013</small></li>

<br/><li>New Baby Mobile<br/><small>July 20, 2013</small></li>

<br/><li>First Sensation of Movement<br/><small>July 30, 2013</small></li>

<br/><li> It's a Boy!<br/><small>September 10, 2013</small></li>

<br/><li> West Coast Baby Shower<br/><small>October 12, 2013</small></li>

<br/><li> East Coast Baby Shower<br/><small>November, 2013</small></li>

<br><li> <b>Due Date</b> <br><small>January 24, 2014</small></li>
</ul>

app/views/home/index.html.erb
<% content_for :title, "baby.lalcohol.com" %>

<h3>News </h3>
My amazing, young, gorgeous, stunning mother will be hosting a "West Coast" Baby Shower for those who want to poke the belly, but are unable to visit me here in DC.
I am nearing the 'no fly trimester' therefore this event will be taking place in October.  
<br/><br/>
We are very grateful to have such wonderful and loving families that show us an incredible amount of support. We are very thankful and excited to see everyone!

<br/> <br/>
<div style="width: 80%; text-align: center; margin: auto;" >
<img src="/WhooosBaby.jpg" />
</div>

app/views/home/milestones.html.erb
<% content_for :title, "Mileestones - baby.lalcohol.com" %>

<h3>Milestones </h3>

Here are some memorable dates of accomplishments!
<br/><br/>

<ul>

<br/><li>Confirmed Pregnancy<br/><small>May 20, 2013</small></li>

<br/><li>Completed First Trimester<br/><small>July 15, 2013</small></li>

<br/><li>Started Second Trimester<br/><small>July 16, 2013</small></li>

app/views/home/pictures.html.erb
<% content_for :title, "Pictures - baby.lalcohol.com" %>


<h3>Pictures </h3>

Here are some fun pictures that have been taken so far!
<br /> <br />

<a href="https://plus.google.com/photos/109337533791433910283/albums/5922175062347930913?authkey=CNfCz6L_rdGD3wE" target="_new" ><img src="/BabyLaLAlbumCover.jpg" ><a/>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "baby.lalcohol.com", root_path, :class => 'brand' %>
<ul class="nav">

     <li>
    <%= link_to 'Events', events_path %>
    </li>

    <li>
    <%= link_to 'Pictures', pictures_path %>
    </li>

    <li>
    <%= link_to 'Milestones', milestones_path %>
    </li>




</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>